version: '3.7'

services:
  db:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  jaeger:
    image: jaegertracing/all-in-one:1.42
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

  django-api:
    container_name: django-api
    build:
      context: ./django_api
    ports:
      - "8001:8001"
    depends_on:
      - db
      - jaeger
    env_file: ./django_api/.env
    volumes:
      - ./django_api:/code
    stdin_open: true
    tty: true
